[package]
name = "real_battery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 'z'
strip = true
panic = 'abort'

[dependencies]
libc = "0.2.144"